import { getFirebaseMessaging } from './firebase';

const FCM_SW_PATH = '/firebase-messaging-sw.js';
const VAPID_KEY = import.meta.env.VITE_FIREBASE_VAPID_KEY || 'BAjpMhHkdyiTm9zd4pYcp8kOkth7FHcId9_swudAH6OSI4brChi_3P0EME_zgwDYc-bGr7ZvwMc4Tnuu8QVlWug';

const loadMessagingHelpers = async () => {
  const messagingModule = await import('https://www.gstatic.com/firebasejs/12.3.0/firebase-messaging.js');
  return {
    getToken: messagingModule.getToken as (messaging: unknown, options: Record<string, unknown>) => Promise<string>,
    onMessage: messagingModule.onMessage as (
      messaging: unknown,
      listener: (payload: { notification?: { title?: string; body?: string; icon?: string } }) => void,
    ) => () => void,
  };
};

export const registerFcmServiceWorker = async (): Promise<ServiceWorkerRegistration | null> => {
  if (!('serviceWorker' in navigator)) {
    console.warn('[FCM] Service workers are not supported in this browser.');
    return null;
  }

  try {
    const registration = await navigator.serviceWorker.register(FCM_SW_PATH, { type: 'module' });
    console.info('[FCM] Service worker registered:', registration.scope);
    return registration;
  } catch (error) {
    console.error('[FCM] Service worker registration failed:', error);
    return null;
  }
};

export const requestNotificationPermission = async (): Promise<string | null> => {
  try {
    if (!('Notification' in window)) {
      console.warn('[FCM] Notifications are not supported in this browser.');
      return null;
    }

    if (Notification.permission === 'denied') {
      console.warn('[FCM] Notification permission is denied. Ask user to enable it in browser settings.');
      return null;
    }

    const messaging = await getFirebaseMessaging();
    if (!messaging) return null;

    const permission = Notification.permission === 'granted'
      ? 'granted'
      : await Notification.requestPermission();

    console.info('[FCM] Notification permission status:', permission);

    if (permission !== 'granted') return null;

    const registration = await registerFcmServiceWorker();
    if (!registration) return null;

    const { getToken } = await loadMessagingHelpers();
    const token = await getToken(messaging, {
      vapidKey: VAPID_KEY,
      serviceWorkerRegistration: registration,
    });

    if (!token) {
      console.warn('[FCM] No FCM token generated by Firebase.');
      return null;
    }

    console.info('[FCM] Generated FCM token:', token);
    return token;
  } catch (error) {
    console.error('[FCM] Failed to request permission/generate token:', error);
    return null;
  }
};

export const setupForegroundNotifications = async (): Promise<(() => void) | undefined> => {
  const messaging = await getFirebaseMessaging();
  if (!messaging) return undefined;

  const { onMessage } = await loadMessagingHelpers();

  return onMessage(messaging, (payload) => {
    console.info('[FCM] Foreground message received:', payload);

    if (Notification.permission === 'granted' && payload.notification?.title) {
      new Notification(payload.notification.title, {
        body: payload.notification.body,
        icon: payload.notification.icon || '/icons/icon-192-dark.png',
      });
    }
  });
};
